apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: creto-enablement

resources:
  - namespace.yaml
  - metering-deployment.yaml
  - oversight-deployment.yaml
  - runtime-deployment.yaml
  - messaging-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: creto-enablement
  app.kubernetes.io/managed-by: kustomize
