apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: creto-enablement-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment

images:
  - name: ghcr.io/creto-systems/enablement/metering
    newTag: staging
  - name: ghcr.io/creto-systems/enablement/oversight
    newTag: staging
  - name: ghcr.io/creto-systems/enablement/runtime
    newTag: staging
  - name: ghcr.io/creto-systems/enablement/messaging
    newTag: staging

configMapGenerator:
  - name: creto-metering-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
  - name: creto-oversight-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
  - name: creto-runtime-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
  - name: creto-messaging-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
